---
  sources: #mandatory, list of source objects distinguished by 'title'; sources can be nested
    -
      title: "BAR Arabidopsis AGI -> Annotation" #mandatory, free text; maps to dcterms:title
      description: "Most recent annotation for given AGI" #optional, free text; maps to dcterms:description
      language: "en-ca" # optional, valid values defined in RFC 4646; maps to dcterms:language
      links: #optional, list of link objects distinguished by 'uri'
        - uri: "http://bar.utoronto.ca/webservices/agiToAnnot.php" #mandatory if defining links, valid URI
          description: "The AGI to Annotation web service" #optional, free text
      license: "Creative Commons 3.0" #optional, free text or valid URI; maps to dcterms:license
      # authors are contributors to this data source
      authors: #optional, list of author objects distinguised by 'name'
        - name: "Nicholas Provart" #mandatory
          email: "provart@utoronta.ca" #optional, valid email
          uri: "http://csb.utoronto.ca/faculty/nicholas-provart/" #optional, valid URI
          role: "Principal Investigator" #optional, free text
          sponsors: #optional, list of sponsors distinguished by 'name'
            - name: "University of Toronto" #mandatory
              uri: "http://www.utoronto.ca/" #optional, valid URI
              address: "123 Main Street, Toronto, Canada" #optional, free text
        - name: "Asher Pasha"
          role: "Software Developer"
          sponsors:
            - name: "University of Toronto"
              uri: "http://www.utoronto.ca/"
      sources: #optional, list of contributing sources distinguished by 'title'
        -
          title: "TAIR"
          description: "The Arabidopsis Information Resource"
          language: "en-us"
          links:
            - uri: "https://www.arabidopsis.org/"
          citations: #optional, list of citations distinguised by 'text'
            - text: "The Arabidopsis Information Resource (TAIR): improved gene annotation and new tools. Nucleic Acids Research 2011" #mandatory, plaintext, maps to dcterms:bibliographicCitation
              uri: "doi:10.1093/nar/gkr1090" # optional, valid DOI for ^ text
          authors:
            - name: "Eva Huala"
              sponsors:
                - name: "Phoenix Bioinformatics"
                - uri: "http://phoenixbioinformatics.org/"
